name: Main workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [2.x, 3.x]
        coverage: [false]
        include:
        - os: ubuntu-latest
          python-version: 3.x
          coverage: true

    steps:
    - name: Check out the project
      uses: actions/checkout@v2.1.0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Cache dependencies (Linux)
      uses: actions/cache@v1.1.2
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache dependencies (macOS)
      uses: actions/cache@v1.1.2
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache dependencies (Windows)
      uses: actions/cache@v1.1.2
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --builtins=FileNotFoundError --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      if: matrix.coverage == false
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
      if: matrix.coverage == false
    - name: Install coverage dependencies
      run: pip install codecov pytest pytest-cov
      if: matrix.coverage == true
    - name: Generate code coverage reports
      run: pytest --cov=./
      if: matrix.coverage == true
    - name: Upload the coverage reports
      run: codecov
      if: matrix.coverage == true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
